name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Use Node.js 18.x
        uses: actions/setup-node@v4
        with:
          node-version: 18.x

      - name: Install client dependencies
        working-directory: ./client
        run: npm ci

      - name: Deploy to GitHub Pages
        working-directory: ./client
        run: npm run deploy
        env:
          CI: false
